#!/usr/bin/env python3
"""FLEET OVERWATCH — arm, inspect, and disarm a per-session overnight overwatch.

An "overwatch" is a Hermes agent cron gated by a deterministic state monitor
(`fleet_state.py`). It wakes only when the watched session's state CHANGES -
working -> idle / needs-input / queued / dead, or a new fleet-daemon event - so a
steadily-working session costs nothing. When it does wake it nudges the session,
answers obvious questions itself, and reports to the human only on major
milestones, large blockers, or major decisions.

WHY THIS EXISTS: the overwatch was previously hand-built as a one-off cron, so it
lived outside the fleet manager and had to be reconstructed by hand for each
session. Arming is now a single command and the discipline lives in the repo
template.

    fleet_overwatch.py arm <session> [--interval 15m] [--focus-file F]
                                   [--name N] [--deliver origin] [--session-short S]
    fleet_overwatch.py status
    fleet_overwatch.py disarm <session> [--remove]

Runtime state (generated monitor wrappers + the armed registry) lives beside the
other fleet state in ~/.hermes/scripts/cc-watch/overwatch/, NOT in this repo.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
# REPO assets (templates) must resolve through the SYMLINK to the real repo, while
# runtime state stays anchored in cc-watch. Using abspath here silently points at
# ~/.hermes/scripts/templates when invoked via the cc-watch symlink.
REPO = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
TEMPLATE = os.path.join(REPO, "templates", "overwatch-prompt.md")

# Runtime state: beside the other fleet state, not in the repo.
STATE = os.path.expanduser("~/.hermes/scripts/cc-watch")
OVERWATCH_DIR = os.path.join(STATE, "overwatch")
ARMED = os.path.join(OVERWATCH_DIR, "armed.json")
SCRIPTS_ROOT = os.path.expanduser("~/.hermes/scripts")

HERMES = os.environ.get("HERMES_BIN") or (
    os.path.expanduser("~/.hermes/hermes-agent/venv/bin/hermes")
    if os.path.exists(os.path.expanduser("~/.hermes/hermes-agent/venv/bin/hermes"))
    else "hermes"
)

WRAPPER = '''#!/usr/bin/env python3
"""GENERATED by fleet_overwatch.py arm — monitor for {session}. Do not hand-edit.

Emits a deterministic state fingerprint for one session so the overwatch cron only
wakes its agent on a real state change. Regenerate by re-arming.
"""
import os, subprocess, sys

ENGINE = {engine!r}
sys.exit(subprocess.run([sys.executable, ENGINE, {session!r}]).returncode)
'''


def _load_armed():
    if not os.path.exists(ARMED):
        return {}
    try:
        return json.load(open(ARMED))
    except (json.JSONDecodeError, OSError):
        return {}


def _save_armed(d):
    os.makedirs(OVERWATCH_DIR, exist_ok=True)
    tmp = ARMED + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(d, fh, indent=2, sort_keys=True)
    os.replace(tmp, ARMED)


def _short(session):
    """Derive a log-matching short name: cc-w-example-1111 -> the example session."""
    parts = session.split("-")
    if len(parts) >= 3 and parts[0] == "cc":
        return parts[2]
    return session


def _render(session, focus, short):
    text = open(TEMPLATE).read()
    return (text.replace("{{SESSION}}", session)
                .replace("{{FOCUS}}", focus.strip() or "(none recorded)")
                .replace("<session-short>", short))


def arm(args):
    session = args.session
    engine = os.path.join(STATE, "fleet_state.py")
    if not os.path.exists(engine):
        print(f"ERROR: monitor engine missing: {engine}", file=sys.stderr)
        print("       (fleet_state.py should be symlinked into cc-watch)", file=sys.stderr)
        return 1

    short = args.session_short or _short(session)
    focus = ""
    if args.focus_file:
        focus = open(os.path.expanduser(args.focus_file)).read()
    elif args.focus:
        focus = args.focus

    # 1. generated per-session monitor wrapper (cron monitor_script takes NO args)
    os.makedirs(OVERWATCH_DIR, exist_ok=True)
    wrapper = os.path.join(OVERWATCH_DIR, f"{session}_state.py")
    with open(wrapper, "w") as fh:
        fh.write(WRAPPER.format(session=session, engine=engine))
    os.chmod(wrapper, 0o755)
    monitor_rel = os.path.relpath(wrapper, SCRIPTS_ROOT)

    # 2. sanity-check the monitor before wiring it to a cron
    probe = subprocess.run([sys.executable, wrapper], capture_output=True, text=True, timeout=30)
    if probe.returncode != 0 or not probe.stdout.strip():
        print(f"ERROR: monitor wrapper produced no state: {probe.stderr.strip()[:200]}",
              file=sys.stderr)
        return 1
    state = probe.stdout.strip()

    # 3. create the cron job (re-arm safe: replace any existing arming for this session
    #    rather than stacking a second identically-named job)
    name = args.name or f"{short}-overwatch"
    existing = _load_armed().get(session)
    if existing:
        prev = existing.get("name", name)
        rm = subprocess.run([HERMES, "cron", "remove", prev],
                            capture_output=True, text=True, timeout=120)
        print(f"  re-arming: removed previous job '{prev}' "
              f"({(rm.stdout or rm.stderr).strip().splitlines()[-1] if (rm.stdout or rm.stderr).strip() else 'ok'})")
    prompt = _render(session, focus, short)
    cmd = [HERMES, "cron", "create", args.interval, prompt,
           "--name", name,
           "--monitor-script", monitor_rel,
           "--continuity",
           "--deliver", args.deliver]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
    out = (r.stdout or "") + (r.stderr or "")
    if r.returncode != 0:
        print(f"ERROR: cron create failed ({r.returncode}):\n{out.strip()[:600]}", file=sys.stderr)
        return 1

    # 4. record it
    d = _load_armed()
    d[session] = {
        "name": name,
        "interval": args.interval,
        "monitor": monitor_rel,
        "wrapper": wrapper,
        "deliver": args.deliver,
        "short": short,
        "armed_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
    }
    _save_armed(d)

    print(f"armed overwatch for {session}")
    print(f"  job name : {name}")
    print(f"  interval : {args.interval} (monitor-gated)")
    print(f"  monitor  : {monitor_rel}  -> {state}")
    print(f"  deliver  : {args.deliver}")
    print(f"  focus    : {'yes' if focus.strip() else 'NONE (no decided-context block)'}")
    print("  " + out.strip().splitlines()[-1] if out.strip() else "")
    return 0


def status(_args):
    d = _load_armed()
    if not d:
        print("no overwatches armed (registry: %s)" % ARMED)
        return 0
    listing = subprocess.run([HERMES, "cron", "list"], capture_output=True, text=True, timeout=120).stdout
    for session, info in sorted(d.items()):
        live = os.path.exists(info["wrapper"])
        job = ""
        for line in listing.splitlines():
            if info["name"] in line:
                job = line.strip()
                break
        print(f"{session}")
        print(f"  name    : {info['name']}")
        print(f"  monitor : {info['monitor']}  ({'present' if live else 'MISSING'})")
        print(f"  armed   : {info.get('armed_at','?')}  interval {info.get('interval','?')}")
        print(f"  cron    : {job or 'not found in cron list'}")
    return 0


def disarm(args):
    d = _load_armed()
    info = d.get(args.session)
    if not info:
        print(f"{args.session} is not armed", file=sys.stderr)
        return 2
    verb = "remove" if args.remove else "pause"
    r = subprocess.run([HERMES, "cron", verb, info["name"]],
                       capture_output=True, text=True, timeout=120)
    print(f"{verb} {info['name']}: {(r.stdout or r.stderr).strip()[:200]}")
    if r.returncode == 0 and args.remove:
        del d[args.session]
        _save_armed(d)
        try:
            os.remove(info["wrapper"])
        except OSError:
            pass
        print("  registry + generated wrapper cleaned up")
    elif r.returncode == 0:
        print("  paused (re-arm or `hermes cron resume` to restore)")
    return r.returncode


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    a = sub.add_parser("arm", help="arm an overwatch for a session")
    a.add_argument("session", help="tmux session name, e.g. cc-w-example-1111")
    a.add_argument("--interval", default="15m")
    a.add_argument("--focus-file", help="file with the ALREADY-DECIDED context block")
    a.add_argument("--focus", help="inline ALREADY-DECIDED context")
    a.add_argument("--name", help="cron job name (default <short>-overwatch)")
    a.add_argument("--deliver", default="origin")
    a.add_argument("--session-short", help="short name used to match daemon log lines")
    a.set_defaults(func=arm)

    s = sub.add_parser("status", help="list armed overwatches")
    s.set_defaults(func=status)

    d = sub.add_parser("disarm", help="pause (or --remove) an overwatch")
    d.add_argument("session")
    d.add_argument("--remove", action="store_true", help="delete the job instead of pausing")
    d.set_defaults(func=disarm)

    args = p.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
